explanation = [
    'Four skeletons dressed in aged clothing and rusting armor lie on the floor in the room against the walls.',
    'This room is filled with masks. You look harder and see the masks are human faces.'
    'The strong, sour-sweet scent of vinegar assaults your nose as you enter this room.',
    'The entire floor of the room has fallen into a second room beneath it.',
    'You open the door to confront a room of odd pillars.',
    'A glow escapes this room through its open doorways. The masonry between every stone emanates an unnatural orange radiance.',
    'This small room is lined with benchlike seats on all the walls.',
    'This hall stinks with the wet, pungent scent of mildew.',
    'This small chamber is a bloody mess.',
    'This tiny room holds a curious array of machinery. Winches and levers project from every wall, and chains with handles dangle from the ceiling.',
    'You open the door and immediately fall. But there is nothing to fall into.',
    'You open the door and a gout of flame rushes at your face. ',
    'Rats inside the room shriek when they hear the door open, then they run in all directions from a putrid corpse lying in the center of the floor. ',
    'Looking into the room, you see other exits blocked by animal carcasses.',
    'Many doors of varied shape, size, and design fill the room ahead.',
    'The room beyond is filled with rubble.',
    'This room is shattered. A huge crevasse shears the chamber in half, and the ground and ceilings are tilted away from it.',
    'There is nothing here. Even the door disappears as soon as you enter.',
    'A cluster of low crates surrounds a barrel in the center of this chamber.',
    'There is nothing here. Even the door disappears as soon as you enter.',
    'You feel the chills in this room before you even open the door.',
    'This tiny room holds a curious array of machinery. Winches and levers project from every wall, and chains with handles dangle from the ceiling.',
    'This chamber holds an odd contraption of metal and wood.',
    'You open the door and are face to face with a giant cochroach wearing a headband.',
    'This room holds six dry circular basins large enough to hold a man and a dry fountain at its center.',
    'You find this chamber lit dimly by guttering candles that squat in small hills of melted wax.',
    'This room is a tomb.',
    'The entire room is empty except for a small black box in the middle of the room.',
    'You cannot see past the long pillars in the room.',
    'This a large ballroom decorated for a party.',
    'The room is made entirely of ice.',
    'You hear the scream of a person begging to be freed but cannot see them in this tiny room.'
    'The scent of earthy decay assaults your nose upon peering through the open door to this room.',
    'You enter a small room and your steps echo.',
    'This could be a training room for combat.',
    'There is nothing in the room but a small TV from 1957.',
    'The room is full of people, alive yet not moving.',
    'As soon as the door opens, you are greeted by the sounds of the ocean but there is no ocean in site.',
    'An abandoned stage sits in the middle of the room. There are no chairs.',
    'The entire room is lined with bookshelves filled with books but you can see right through them.'
]


title = [
    'Hallowward Sanctuary',
    'Spirespell Nest',
    'Wolflance Escape',
    'Scarlet Hideaway',
    'Bitterhorn Lair',
    'Mysterious Peaks',
    'Ashborn Haven',
    'Infinity Retreat',
    'Blackword Cover',
    'Autumn Sanctum',
    'Fire Lair',
    'Castle Hill Manor',
    'Retribution Den',
    'Saurland Base',
    'Serene Delves',
    'Trident Cave',
    'Celestial Hideout',
    'House of the Black Widow',
    'Dreamridge Labyrinth',
    'Lawful State',
    'Sad Quarters',
    'Witchs Cove',
    'Shrews Empire',
    'Unnamed Angels Province',
    'Bronze Cemetaries',
    'Celestial Hideout',
    'Ivory Harbor',
    'Shadow Province',
    'Infernal Slopes',
    'Alluring Tower',
    'Galaxy Theatre',
    'Haunted Cult',
    'The Sphere',
    'Whispering Shadows Lair',
    'Sapphire Room',
    'Brownpool Hall',
    'Kraken Refuge',
    'Frozen Forest',
    'Imagined Terrain',
    'Shrews Empire'
]