# Generated by Django 3.0.5 on 2020-04-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20200429_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
